config/routes.rb
Rails.application.routes.draw do
  root 'stores#index'
  resources :reviews
  resources :employees
  resources :departments
  resources :stores
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
    has_many :departments
    has_many :reviews
    def count_reviews
        points = 0
        total_re = self.reviews.count
        self.reviews.all.each do |r|
            case r.note
            when  'awsome'
                points += 6
            when 'very good', 'awsome'
                points += 5
            when 'good'
                points += 4.5
            when 'alright'
                points += 3.5
            when 'whatever'
                points += 2.5
            when 'bad'
                points += 1
            when 'very bad'
                points += 0
            else
                points += 0
            end

        end
        return (points/total_re).round(2)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all

  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @departments = @store.departments
    @reviews = @store.reviews
    
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:name, :description, :url, :status, :code, :address, :city, :state, :zip, :country)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>
<h1 class="text-center"><Strong>STORE</Strong></h1>
<%= link_to 'Create a new store', new_store_path, class:"btn btn-primary mb-3 mt-3" %>
    <div class="row">
      <div class="card-deck">
        <% @stores.each do |store| %>
        <div class="col-4">
          <div class="card mb-3 h-200">
            <div class="card-header">
              <h4><%= store.name %></h4>
            </div>
            <div class="card-body">
              <p><strong>Description: </strong><%= store.description %></p>
              <P><strong>Counttry: </strong><%= store.country %></P>
              <p><strong>Url: </strong><%= store.url %></p>
              <p><strong>reviews: </strong><%=store.count_reviews  %></p> 
              <div class="mt-4 text-center"> 
                <%= link_to 'Show', store , class:"btn btn-primary btn-sm"%>
                <%= link_to 'Edit', edit_store_path(store), class:"btn btn-warning btn-sm" %>
                <%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
</div>
<br>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <strong>Name:</strong>
  <%= @store.name %>
</h2>

<h4>
  <strong>Description:</strong>
  <%= @store.description %>
</h4>
<h4> Reviews: <%=@store.count_reviews%>/5</h4>

<div class="progress mb-4 mt-4 col-4">
  <div class="progress-bar progress-bar" role="progressbar" style="width: <%=@store.count_reviews*10*2%>%" aria-valuenow="5" aria-valuemin="0" aria-valuemax="20"><%=@store.count_reviews%></div>
</div>


<%= link_to 'Edit', edit_store_path(@store), class:"btn btn-sm btn-primary" %>
<%= link_to 'Back', stores_path, class:"btn btn-sm btn-secondary" %>
<hr>
<h3>deparments</h3><br>
      <div class="row">
      <% @departments.each do |d| %>
        <div class="col-6">  
      
          <div class="card mb-4">
            <h3 class="card-header"> <%= d.name %></h3>
            <div class="card-body">
                  <h5> Employee names in the department </h5>
                  <%d.employees.all.each do |e|%>
                    <div class="mr-2"><%=e.first_name%></div>
                  <%end%>   
                <div class="row m-4"> 
                  <%= link_to 'Show', d, class:"btn btn-sm btn-primary m-2" %><br>
                  <%= link_to 'Edit', edit_department_path(d) ,class:"btn btn-sm btn-warning m-2"%> <br>
                  <%= link_to 'Destroy', d, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-sm btn-danger m-2" %>
                </div> 
            </div>
          </div>
        </div>
      <% end %>
      </div>

<hr>

<h3>Reviews from the employee</h3>

        <div class="card">
          <div class="card-body">
            <div class="row"> 
              <p class="col-3"><strong>Last name</strong></p>
              <p class="col-3"><strong>Department</strong></p>
              <p class="col-3"><strong>Reviews</strong></p>
            </div> 
          </div>
        </div>

     <% @reviews.each do |s| %>
        <div class="card">
          <div class="card-body">
            <div class="row"> 
              <p class="col-3"><strong><%=s.employee.last_name%></strong></p>
              <p class="col-3"><%=s.employee.department.name%></p>
              <p class="col-4"><%= s.note %></p>
            </div> 
          </div>
        </div>
        
      <% end %>
  